#### Load Numpy (remember to "pip install numpy" first)

In [202]:
import numpy as np

## The Basics

In [203]:
a = np.array([1,2,3], dtype ='int32')
print(a)

[1 2 3]


In [204]:
b = np.array([[34.9,5.65,3,5,7],[34,5,35,35,67]])
print(b)

[[34.9   5.65  3.    5.    7.  ]
 [34.    5.   35.   35.   67.  ]]


In [205]:
#Get dimension
a.ndim

1

In [206]:
#Get shape
b.shape

(2, 5)

In [207]:
#Get Shape
a.dtype

dtype('int32')

In [208]:
#Get size of one element
a.itemsize

4

In [209]:
#Get the total size of all elements
a.nbytes

12

In [210]:
#Get number of elements in  an array
a.size

3

### Accessing/Changing specific elements, rows, columns,etc.

In [211]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [212]:
#Get a specific element [r,c]
a[1,3]

11

In [213]:
# Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [214]:
# Get a specific column
a[:,6]

array([ 7, 14])

In [215]:
# Gettting a  little more Fancy with this [startindex:endIndex:stepsize]
a[0,1:-2:2]

array([2, 4])

In [216]:
a[1,4] = 556
print(a)

a[:,2] = [64,97]
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11 556  13  14]]
[[  1   2  64   4   5   6   7]
 [  8   9  97  11 556  13  14]]


*3D-Array Example

In [217]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [218]:
# Get a specific element (work out in)
b[0,1,1]  ##Here the first indicates outer rows,second number
## Indicates inner rows and the last but not least Indicates
## Columns

4

In [219]:
# replace
b[:,1,:] = np.array([[6,48],[6,9]])

In [220]:
b

array([[[ 1,  2],
        [ 6, 48]],

       [[ 5,  6],
        [ 6,  9]]])

### Initializing Different Types of Arrays

In [221]:
# All 0s matrix
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [222]:
# All 1s matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [223]:
# Any other number
np.full((2,3),99,dtype="float32")

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [224]:
# Any other number (full_like)
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [225]:
# Random decimal numbers
np.random.rand(3,2)

array([[0.02581538, 0.62586246],
       [0.65911082, 0.14950839],
       [0.44786542, 0.32700113]])

In [226]:
# Random integer values
np.random.randint(-3,8,size=(3,3))

array([[-1,  6,  1],
       [ 0,  1,  4],
       [ 4,  3,  7]])

In [227]:
# Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [228]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [229]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [230]:
a = np.array([1,3,4])
b = a.copy()
print(a)
b[0] = 86
print(b)

[1 3 4]
[86  3  4]


#### Mathematics

In [231]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [232]:
a + 2

array([3, 4, 5, 6])

In [233]:
a - 2

array([-1,  0,  1,  2])

In [234]:
a * 2

array([2, 4, 6, 8])

In [235]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [236]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [237]:
a ** 2

array([ 1,  4,  9, 16])

In [238]:
# Take the sin (trigonometric's)
a = np.sin(a)
print(a)
np.cos(a)
print(a)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


#For a Lot more read the Documentation by using the given link (https://docs.scipy.org/doc/numpy/reference/routines.math.html)


#### Linear Algebra

In [239]:
a = np.ones((2,4))
print(a)

b = np.full((4,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]]


array([[8., 8.],
       [8., 8.]])

In [240]:
# Find the determinant
c = np.identity(4)
np.linalg.det(c)

1.0

##Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

#Determinant
#Trace
#Singular Vector Decomposition
#Eigenvalues
#Matrix Norm
#Inverse
#Etc...

#### Statistics

In [241]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [242]:
np.min(stats)

1

In [243]:
np.max(stats, axis=1)

array([3, 6])

In [244]:
np.sum(stats,axis=0)

array([5, 7, 9])

#### Recognizing Arrays

In [245]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

After = before.reshape((4,2))
print(After)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [246]:
# Vertically Stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [247]:
# Horizontal Stacking Vectors
h1 = np.array([[4,5,6,2],[8,0,7,7]])
h2 = np.ones((2,3))
np.hstack([h1,h2])
## We can either use [,] braces or (,) parenthesis to declare h1,h2 or v1,v2 in stacking.


array([[4., 5., 6., 2., 1., 1., 1.],
       [8., 0., 7., 7., 1., 1., 1.]])

#### Miscellaneous

##### Load data from File

In [248]:
filedata = np.loadtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Boolean Masking and Advanced Indexing

In [249]:
~((filedata > 50)  & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])